apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: test-mvp-component-eomm
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - env:
        - name: var_name
          value: test
        image: quay.io/redhat-appstudio-qe/test-images@sha256:2656b6f352051f1e491dc9eceed0af112b4b84d634ad37736b63a634669a73ee
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
